package com.iok.gfweather.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.iok.gfweather.db.Wallpaper;

import com.iok.gfweather.db.WallpaperDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig wallpaperDaoConfig;

    private final WallpaperDao wallpaperDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        wallpaperDaoConfig = daoConfigMap.get(WallpaperDao.class).clone();
        wallpaperDaoConfig.initIdentityScope(type);

        wallpaperDao = new WallpaperDao(wallpaperDaoConfig, this);

        registerDao(Wallpaper.class, wallpaperDao);
    }
    
    public void clear() {
        wallpaperDaoConfig.getIdentityScope().clear();
    }

    public WallpaperDao getWallpaperDao() {
        return wallpaperDao;
    }

}
